# -*- coding: utf-8 -*-
"""QUIZ-1 ans.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kSd4_ksQZcuelbwZq_Y8mKDc4hydaGT3
"""

import numpy as np
from matplotlib import pyplot as plt

t = np.linspace(0, 5, 1000)
x = [-1,0,1,2,3,4,5,6]
y = [0,1,1,1,1,-2,-2,0]
plt.xlabel('n');
plt.ylabel('h[n]');
plt.scatter(x, y, marker= ".", s=30)
plt.title('Plot of impulse response');
plt.show()